from src.ui.pyside_ui.settings import ANIMATION_DURATION, MAINWINDOW_HEIGHT, MAINWINDOW_RESIZE_RANGE, MAINWINDOW_WIDTH

__all__ = [
    "ANIMATION_DURATION",
    "MAINWINDOW_HEIGHT",
    "MAINWINDOW_RESIZE_RANGE",
    "MAINWINDOW_WIDTH",
]
