# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3.10
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-added-large-files
        exclude: src/ui/forms/fonts/
    -   id: check-ast
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: check-shebang-scripts-are-executable
    -   id: check-symlinks
    -   id: check-xml
    -   id: check-yaml
    -   id: destroyed-symlinks
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: fix-encoding-pragma
    -   id: pretty-format-json
        exclude: |
            (?x)^(
                .vscode/launch.json|
                .vscode/settings.json
            )$
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        language_version: python
-   repo: https://github.com/psf/black
    rev: "23.3.0"
    hooks:
    -   id: black
        args: [-l 120]
        language_version: python3.10
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.910"
    hooks:
    -   id: mypy
        args: [--warn-unused-configs,
               --warn-redundant-casts,
               --warn-unused-ignores,
               --strict-equality,
               --check-untyped-defs,
               --disallow-subclassing-any,
               --disallow-untyped-decorators,
               --disallow-any-generics,
               --disallow-untyped-calls,
               --disallow-incomplete-defs,
               --disallow-untyped-defs,
               --no-implicit-reexport,
               --warn-return-any]
        additional_dependencies:
            - "types-PyYAML"
            - pydantic
-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: "v3.0.0a4"
    hooks:
    -   id: pylint
        exclude: |
            (?x)^(
                moc_*.py|
                files_rc.py
            )$
        args: [--rcfile=setup.cfg]
-   repo: https://github.com/pycqa/flake8
    rev: "6.0.0"
    hooks:
    -   id: flake8
        args: []
-   repo: https://github.com/myint/docformatter
    rev: "v1.4"
    hooks:
    -   id: docformatter
        args: [--in-place]
