sonar.projectKey=python-standalone-gui-template
sonar.projectName=python-standalone-gui-template
sonar.projectVersion=1.0

sonar.projectBaseDir=/usr/src

sonar.sources=src
sonar.tests=tests

sonar.test.inclusions=tests/**/*

sonar.sourceEncoding=UTF-8

sonar.python.version=3.11

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.ruff.reportPaths=ruff-report.json

sonar.javascript.lcov.reportPaths=src/ui/react_ui/frontend/coverage/lcov.info
sonar.typescript.lcov.reportPaths=src/ui/react_ui/frontend/coverage/lcov.info

sonar.exclusions=\
**/__pycache__/**,\
**/.venv/**,\
**/node_modules/**,\
**/dist/**,\
**/build/**,\
**/htmlcov/**,\
**/coverage/**,\
**/*.js,\
**/ui_*.py,\
**/*.test.ts,\
**/*.test.tsx,\
**/*.spec.ts,\
**/*.spec.tsx